[connections]
[connections.supabase]
url = "https://mqjkcmqcjnvmecamwmbz.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xamtjbXFjam52bWVjYW13bWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0ODIyMTAsImV4cCI6MjA5NTA1ODIxMH0.sLJ1ODzHeu5M5VodamSDQEyru3JnaXOmymR_wPA3ENo"

[credentials]
senha_instrutor = "CCM2026@Gestao" 
